package com.example.tuoni.payload;

import com.shelldot.tuoni.plugin.sdk.common.exceptions.SerializationException;
import com.shelldot.tuoni.plugin.sdk.payload.Payload;
import com.shelldot.tuoni.plugin.sdk.payload.PayloadType;
import java.nio.ByteBuffer;

public class TemplatePayload implements Payload {

  @Override
  public String getFileName() {
    // TODO: Choose the output filename and format.
    // Return the suggested download filename for the bytes produced by serialize(). Choose an
    // extension matching the actual artifact format (for example an executable, DLL, or raw
    // binary), and include distinguishing build information if useful. This is artifact metadata;
    // it does not write the file or choose a server-side storage directory.
    return "template-payload.exe";
  }

  @Override
  public PayloadType getPayloadType() {
    // Report the operating system and architecture of the generated bytes. Keep this consistent
    // with the creating template's declared type and with the payload program's build target.
    return TemplatePayloadTemplate.TYPE;
  }

  @Override
  public ByteBuffer serialize() throws SerializationException {
    // TODO: Build the final downloadable artifact from the inputs captured during createPayload().
    // Load or generate the payload program bytes, incorporate the selected listener code and its
    // configuration using the format that the payload program understands, and apply validated
    // build options. Return a buffer whose remaining bytes are exactly the complete output file;
    // reset its position after writing and avoid modifying a shared template buffer in place.
    // Missing resources, unsupported listener representations, or failed binary transformations
    // must produce SerializationException with a useful cause rather than a partial artifact.
    throw new SerializationException("TODO: Implement payload serialization.");
  }
}
